#!/bin/bash
#
# Perform necessary sensu setup steps
# after package is installed.
#

PROGNAME=$(basename $0)

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

prefix="contegix-"
install_dir="/opt/contegix/sensu"
sensu_services="sensu-client sensu-service" #sensu-server sensu-api sensu-dashboard"
rhel7_services="sensu-client"
if [ -f /etc/redhat-release ]; then
  os_family="RedHat"
  os_major_rev="$(perl -pe 's/.*release (\d+)\.\d+.*/$1/' /etc/redhat-release)"
elif [ -f /etc/lsb-release ]; then
  . /etc/lsb-release
  os_family=$DISTRIB_ID
  os_major_rev=$DISTRIB_RELEASE
else
  os_family="Unknown"
fi

# Install package - add services and change permissions
# On first install, register the init scripts but disable services.
# User should choose the services they want to run after install

# Install package - add user
# Create sensu group
if ! getent group ${prefix}sensu >/dev/null; then
	groupadd -r ${prefix}sensu -g 391
fi

# Create sensu user
if ! getent passwd ${prefix}sensu >/dev/null; then
	useradd -r -u 391 -g ${prefix}sensu -d ${install_dir} \
    		-s /bin/bash -c "Sensu Monitoring Framework" ${prefix}sensu
fi


# link logrotate configuration
[ -h /etc/logrotate.d/${prefix}sensu ] || ln -s ${install_dir}/etc/logrotate.d/sensu /etc/logrotate.d/${prefix}sensu

# Change permissions
chown -R ${prefix}sensu:${prefix}sensu ${install_dir}/etc/sensu
chown -R ${prefix}sensu:${prefix}sensu ${install_dir}/var/

# Add systemd service definitions if on EL 7
if [ "${os_major_rev}" == "7" -a "${os_family}" == "RedHat" ]; then
  for service in $rhel7_services; do
    cp -f ${install_dir}/usr/lib/systemd/system/${prefix}${service}.service /usr/lib/systemd/system/${prefix}${service}.service
    systemctl daemon-reload
    systemctl enable ${prefix}${service}
  done
elif [ "${os_family}" == "RedHat" ]; then
  for service in $sensu_services; do
    if [ ! -e /etc/init.d/${prefix}$service ] ; then 
      ln -s ${install_dir}/etc/init.d/$service /etc/init.d/${prefix}${service}
      chkconfig --add ${prefix}$service
      chkconfig ${prefix}$service off
    fi
  done
elif [ "${os_family}" == "Ubuntu" -o "${os_family}" == "Debian" ]; then
  for service in $sensu_services; do
    if [ ! -e /etc/init.d/${prefix}$service ] ; then 
      ln -s ${install_dir}/etc/init.d/$service /etc/init.d/${prefix}${service}
    fi
  done
fi

exit 0
