#!/bin/bash
# Perform preinstall steps for the Sensu RPM

install_dir="/opt/contegix/sensu"

/etc/init.d/contegix-sensu-client stop

if [ -d "${install_dir}/embedded" ]; then
  rm -rf "${install_dir}/embedded"
fi
