#!/bin/bash
#
# Perform necessary sensu removal steps
# before package is uninstalled.
#

prefix="contegix-"
install_dir="/opt/contegix/sensu"
sensu_services="sensu-client sensu-service" # sensu-server sensu-api sensu-dashboard"

if [ -f /etc/redhat-release ]; then
  os_family="RedHat"
else
  os_family="Unknown"
fi
os_major_rev="$(perl -pe 's/.*release (\d+)\.\d+.*/$1/' /etc/redhat-release)"

# upgrade

# uninstall
if [ "${1}" -eq "0" ] ; then

	# Disable and stop sensu services
	if [ "${os_major_rev}" == "7" -a "${os_family}" == "RedHat" ] ; then
		service="${prefix}sensu-client"
		if [ -e /etc/systemd/system/${service}.service ] ; then
			service status ${service} 2>&1 > /dev/null && service stop ${service}
			systemctl disable ${service}
			rm -f /etc/systemd/system/${service}
			systemctl daemon-reload
		fi
	else

		for service in $sensu_services; do
			service="${prefix}${service}"
			if [ -h /etc/init.d/${service} ] ; then
				chkconfig ${service} off
				chkconfig --del ${service}
				/etc/init.d/${service} status 2>&1 > /dev/null && /etc/init.d/${service} stop
				rm -f /etc/init.d/${service}
			fi
		done
	fi
	# unlink logroate config
	[ -e /etc/logrotate.d/${prefix}sensu ] && rm -f /etc/logrotate.d/${prefix}sensu

fi 

exit 0
